// examples/react examples/employee-mgmt-react-app/src/components/shared/Header.js
import React from 'react';
import { NavLink } from "react-router-dom";

//Functional Component
function Header() {
    return (
        <header>
            <nav className="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <a className="navbar-brand" href="#">Employee Management App</a>
                <button
                    className="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarsExampleDefault"
                    aria-controls="navbarsExampleDefault"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span className="navbar-toggler-icon" />
                </button>
                <div className="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul className="navbar-nav mr-auto">
                        <li className="nav-item active">
                            <NavLink to="/" 
                                className="nav-link">
                                Home <span className="sr-only">(current)</span>
                            </NavLink>
                        </li>
                        <li className="nav-item">
                            <NavLink to="/employees" 
                            className="nav-link">
                                Employees</NavLink>
                        </li>
                        <li className="nav-item">
                            <NavLink to="/about" 
                            className="nav-link">About</NavLink>
                        </li>

                    </ul>

                </div>
            </nav>;
        </header>
    )
}

export default Header;

// examples/react examples/employee-mgmt-app/src/app/shared/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html', // html
  styleUrls: ['./header.component.css'] // css
})
export class HeaderComponent implements OnInit {
  // ts
  constructor() { }

  ngOnInit() {
  }
  
}

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand app-name" href="#">Employee Management App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <app-nav>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sign in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sign up</a>
                </li>
            </app-nav>
        </div>
    </nav>
</header>
